import type { InsertCategory, InsertBrand, InsertProduct } from "@shared/schema";
import { extendedProducts, extendedBrands } from './products-data';

export const seedCategories: InsertCategory[] = [
  { name: "Skin Care", slug: "skin-care", description: "Cleansers, moisturizers, and treatments" },
  { name: "Hair Care", slug: "hair-care", description: "Shampoos, serums, and treatments" },
  { name: "Makeup", slug: "makeup", description: "Lipsticks, foundations, and palettes" },
  { name: "Fragrance", slug: "fragrance", description: "Perfumes and body mists" },
  { name: "Sunscreen", slug: "sunscreen", description: "SPF protection for all skin types" },
  { name: "Baby Care", slug: "baby", description: "Gentle products for babies" },
  { name: "Vitamins", slug: "vitamins", description: "Supplements and wellness products" },
  { name: "Medicines", slug: "medicines", description: "OTC medicines and healthcare" },
];

export const seedBrands: InsertBrand[] = [
  { name: "Abbott", slug: "abbott", description: "Global healthcare company" },
  { name: "AcneRid", slug: "acnerid", description: "Acne treatment solutions" },
  { name: "Aichun Beauty", slug: "aichun-beauty", description: "Beauty and skincare products" },
  { name: "Anexa", slug: "anexa", description: "Healthcare products" },
  { name: "ANUA", slug: "anua", description: "Korean skincare brand" },
  { name: "Aptamil", slug: "aptamil", description: "Baby nutrition" },
  { name: "Armani", slug: "armani", description: "Luxury fragrances" },
  { name: "Aveeno", slug: "aveeno", description: "Natural skincare" },
  { name: "Axe", slug: "axe", description: "Men's grooming" },
  { name: "Babi Mild", slug: "babi-mild", description: "Baby care products" },
  { name: "CeraVe", slug: "cerave", description: "Developed with dermatologists" },
  { name: "Clean & Clear", slug: "clean-clear", description: "Skincare for teens" },
  { name: "COSRX", slug: "cosrx", description: "Korean skincare" },
  { name: "Dove", slug: "dove", description: "Real beauty" },
  { name: "Garnier", slug: "garnier", description: "Natural beauty" },
  { name: "Jenpharm", slug: "jenpharm", description: "Professional skincare solutions" },
  { name: "Johnson's", slug: "johnson-s", description: "Baby care trusted brand" },
  { name: "Kendamil", slug: "kendamil", description: "British baby formula" },
  { name: "Mistine", slug: "mistine", description: "Thai beauty brand" },
  { name: "Neutrogena", slug: "neutrogena", description: "Dermatologist recommended" },
  { name: "Nike", slug: "nike", description: "Sports fragrances" },
  { name: "Nivea", slug: "nivea", description: "Trusted skincare" },
  { name: "Pond's", slug: "pond-s", description: "Skincare classics" },
  { name: "Sudocrem", slug: "sudocrem", description: "Healing cream" },
  { name: "Acure", slug: "acure", description: "Clean beauty brand" },
  { name: "Centella", slug: "centella", description: "Skincare solutions" },
  { name: "Syntax", slug: "syntax", description: "Healthcare products" },
  { name: "Shaheen Chemist", slug: "shaheen-chemist-commercial-market", description: "Quality pharmacy products" },
];

export interface SeedProductData {
  name: string;
  slug: string;
  description: string;
  price: number;
  comparePrice: number | null;
  images: string[];
  categorySlug: string;
  brandSlug: string;
  stock: number;
  isFeatured: boolean;
  isActive: boolean;
  sku: string;
  tags: string[];
}

export const seedProducts: SeedProductData[] = [
  {
    name: "Ensure Milk Powder Vanilla, 850 g",
    slug: "ensure-milk-powder-vanilla-850-g",
    description: "Ensure is a source of complete, balanced nutrition for supplemental use with or between meals. It may benefit patients who have malnutrition, are at nutritional risk, are experiencing involuntary weight loss.",
    price: 6375,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign-2024-08-26T161006.179.png"],
    categorySlug: "baby",
    brandSlug: "abbott",
    stock: 50,
    isFeatured: true,
    isActive: true,
    sku: "ENS-VAN-850",
    tags: ["Nutritional Supplement", "Powder Milk"]
  },
  {
    name: "Ensure Milk Powder Chocolate, 850 g",
    slug: "ensure-milk-powder-chocolate-850-g",
    description: "Ensure is a source of complete, balanced nutrition for supplemental use with or between meals. Chocolate flavored. High in Omega 3.",
    price: 6375,
    comparePrice: 5750,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign-2024-08-26T161217.476.png"],
    categorySlug: "baby",
    brandSlug: "abbott",
    stock: 50,
    isFeatured: false,
    isActive: true,
    sku: "ENS-CHO-850",
    tags: ["Nutritional Supplement", "Powder Milk"]
  },
  {
    name: "Abbott PediaSure Strawberry, 850 g",
    slug: "abbott-pediasure-strawberry-850g",
    description: "PediaSure Powder with TripleSure Formula. Contains the clinically proven TripleSure System to support growth, promote immunity and help build a healthy appetite.",
    price: 7039,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign-2024-08-26T160224.225.png"],
    categorySlug: "baby",
    brandSlug: "abbott",
    stock: 50,
    isFeatured: true,
    isActive: true,
    sku: "PED-STR-850",
    tags: ["Nutritional Supplement", "Powder Milk"]
  },
  {
    name: "Abbott PediaSure Chocolate, 850 g",
    slug: "abbott-pediasure-chocolate-850g",
    description: "PediaSure Powder with TripleSure Formula. Unique triple protein complex to help support growth and development.",
    price: 7039,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign-2024-08-26T160428.162.png"],
    categorySlug: "baby",
    brandSlug: "abbott",
    stock: 50,
    isFeatured: true,
    isActive: true,
    sku: "PED-CHO-850",
    tags: ["Nutritional Supplement", "Powder Milk"]
  },
  {
    name: "Abbott Pediasure Chocolate Milk Powder, 400g",
    slug: "abbott-pediasure-chocolate-milk-powder-400g",
    description: "PediaSure contains the clinically proven TripleSure System to support growth, promote immunity and help build a healthy appetite.",
    price: 3530,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_4_2a17e29c-5e14-4c51-982f-b4b87ef3e9ab.png"],
    categorySlug: "baby",
    brandSlug: "abbott",
    stock: 50,
    isFeatured: false,
    isActive: true,
    sku: "PED-CHO-400",
    tags: ["Baby"]
  },
  {
    name: "AcneRid BP 2.5% Gel, 30g",
    slug: "acnerid-bp-2-5-gel-30g",
    description: "Benzoyl Peroxide gel for acne treatment. Helps clear acne and prevent new breakouts.",
    price: 450,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_5_d73ab79c-6a40-44b3-8279-d61a87efaa4e.png"],
    categorySlug: "skin-care",
    brandSlug: "acnerid",
    stock: 100,
    isFeatured: false,
    isActive: true,
    sku: "ACN-BP-25",
    tags: ["Skin Care", "Acne Treatment"]
  },
  {
    name: "Aichun Beauty 24K Gold Face Serum, 30ml",
    slug: "aichun-beauty-24k-gold-serum-30ml",
    description: "Luxurious 24K gold serum for anti-aging and skin brightening. Helps reduce fine lines and improve skin texture.",
    price: 1299,
    comparePrice: 1599,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_6_9f4c7c22-9a17-4bf6-b3da-6a1d5f13c19b.png"],
    categorySlug: "skin-care",
    brandSlug: "aichun-beauty",
    stock: 75,
    isFeatured: true,
    isActive: true,
    sku: "AIC-GOLD-30",
    tags: ["Skin Care", "Face Oil"]
  },
  {
    name: "ANUA Heartleaf 77% Soothing Toner, 250ml",
    slug: "anua-heartleaf-77-soothing-toner-250ml",
    description: "Korean skincare toner with 77% Heartleaf extract. Soothes and hydrates sensitive skin while controlling sebum.",
    price: 3999,
    comparePrice: 4500,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_7_8a1b5c3d-4e2f-6g7h-8i9j-0k1l2m3n4o5p.png"],
    categorySlug: "skin-care",
    brandSlug: "anua",
    stock: 60,
    isFeatured: true,
    isActive: true,
    sku: "ANU-HLT-250",
    tags: ["Skin Care", "Korean Skincare", "Toner"]
  },
  {
    name: "Aptamil Gold+ Stage 1 Infant Formula, 400g",
    slug: "aptamil-gold-stage-1-400g",
    description: "Premium infant formula with Pronutra+ blend. Suitable for babies from birth to 6 months.",
    price: 3200,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_8_1b2c3d4e-5f6g-7h8i-9j0k-1l2m3n4o5p6q.png"],
    categorySlug: "baby",
    brandSlug: "aptamil",
    stock: 40,
    isFeatured: false,
    isActive: true,
    sku: "APT-G1-400",
    tags: ["Baby", "Powder Milk"]
  },
  {
    name: "Aptamil Gold+ Stage 2 Follow-On Formula, 400g",
    slug: "aptamil-gold-stage-2-400g",
    description: "Premium follow-on formula for babies 6-12 months. Contains essential vitamins and minerals.",
    price: 3200,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_9_2c3d4e5f-6g7h-8i9j-0k1l-2m3n4o5p6q7r.png"],
    categorySlug: "baby",
    brandSlug: "aptamil",
    stock: 40,
    isFeatured: false,
    isActive: true,
    sku: "APT-G2-400",
    tags: ["Baby", "Powder Milk"]
  },
  {
    name: "Giorgio Armani Acqua di Gio, 100ml",
    slug: "armani-acqua-di-gio-100ml",
    description: "Iconic men's fragrance with fresh aquatic notes. A timeless scent inspired by the Mediterranean sea.",
    price: 18500,
    comparePrice: 22000,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_10_3d4e5f6g-7h8i-9j0k-1l2m-3n4o5p6q7r8s.png"],
    categorySlug: "fragrance",
    brandSlug: "armani",
    stock: 25,
    isFeatured: true,
    isActive: true,
    sku: "ARM-ADG-100",
    tags: ["Fragrance", "Perfume", "Men"]
  },
  {
    name: "Aveeno Daily Moisturizing Lotion, 354ml",
    slug: "aveeno-daily-moisturizing-lotion-354ml",
    description: "Clinically proven to moisturize for 24 hours. Made with natural colloidal oatmeal.",
    price: 2850,
    comparePrice: 3200,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_11_4e5f6g7h-8i9j-0k1l-2m3n-4o5p6q7r8s9t.png"],
    categorySlug: "skin-care",
    brandSlug: "aveeno",
    stock: 80,
    isFeatured: true,
    isActive: true,
    sku: "AVE-DML-354",
    tags: ["Skin Care", "Lotion"]
  },
  {
    name: "Aveeno Skin Relief Body Wash, 354ml",
    slug: "aveeno-skin-relief-body-wash-354ml",
    description: "Gentle body wash for dry, sensitive skin. Formulated with natural oatmeal.",
    price: 2650,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_12_5f6g7h8i-9j0k-1l2m-3n4o-5p6q7r8s9t0u.png"],
    categorySlug: "skin-care",
    brandSlug: "aveeno",
    stock: 70,
    isFeatured: false,
    isActive: true,
    sku: "AVE-SRB-354",
    tags: ["Skin Care", "Body Wash"]
  },
  {
    name: "Axe Dark Temptation Body Spray, 150ml",
    slug: "axe-dark-temptation-body-spray-150ml",
    description: "Irresistible chocolate scented body spray. Long-lasting fragrance for all-day freshness.",
    price: 899,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_13_6g7h8i9j-0k1l-2m3n-4o5p-6q7r8s9t0u1v.png"],
    categorySlug: "fragrance",
    brandSlug: "axe",
    stock: 120,
    isFeatured: false,
    isActive: true,
    sku: "AXE-DT-150",
    tags: ["Fragrance", "Body Spray", "Men"]
  },
  {
    name: "Babi Mild Baby Lotion, 400ml",
    slug: "babi-mild-baby-lotion-400ml",
    description: "Gentle baby lotion with natural extracts. Keeps baby's skin soft and moisturized.",
    price: 750,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_14_7h8i9j0k-1l2m-3n4o-5p6q-7r8s9t0u1v2w.png"],
    categorySlug: "baby",
    brandSlug: "babi-mild",
    stock: 90,
    isFeatured: false,
    isActive: true,
    sku: "BAB-LOT-400",
    tags: ["Baby", "Lotion"]
  },
  {
    name: "Babi Mild Baby Powder, 380g",
    slug: "babi-mild-baby-powder-380g",
    description: "Ultra-fine baby powder that keeps baby fresh and comfortable. Gentle formula for sensitive skin.",
    price: 550,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_15_8i9j0k1l-2m3n-4o5p-6q7r-8s9t0u1v2w3x.png"],
    categorySlug: "baby",
    brandSlug: "babi-mild",
    stock: 100,
    isFeatured: false,
    isActive: true,
    sku: "BAB-POW-380",
    tags: ["Baby", "Powder"]
  },
  {
    name: "CeraVe Moisturizing Cream, 453g",
    slug: "cerave-moisturizing-cream-453g",
    description: "Rich, non-greasy, fast-absorbing cream that provides 24-hour hydration. Contains essential ceramides.",
    price: 4500,
    comparePrice: 4800,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_16_9j0k1l2m-3n4o-5p6q-7r8s-9t0u1v2w3x4y.png"],
    categorySlug: "skin-care",
    brandSlug: "cerave",
    stock: 60,
    isFeatured: true,
    isActive: true,
    sku: "CER-MC-453",
    tags: ["Skin Care", "Moisturizer"]
  },
  {
    name: "CeraVe Hydrating Cleanser, 236ml",
    slug: "cerave-hydrating-cleanser-236ml",
    description: "Gentle, non-foaming cleanser that hydrates while cleansing. Contains hyaluronic acid and ceramides.",
    price: 2950,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_17_0k1l2m3n-4o5p-6q7r-8s9t-0u1v2w3x4y5z.png"],
    categorySlug: "skin-care",
    brandSlug: "cerave",
    stock: 55,
    isFeatured: true,
    isActive: true,
    sku: "CER-HC-236",
    tags: ["Skin Care", "Cleanser"]
  },
  {
    name: "CeraVe Foaming Cleanser, 236ml",
    slug: "cerave-foaming-cleanser-236ml",
    description: "Refreshing gel cleanser for normal to oily skin. Removes excess oil without disrupting skin barrier.",
    price: 2950,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_18_1l2m3n4o-5p6q-7r8s-9t0u-1v2w3x4y5z6a.png"],
    categorySlug: "skin-care",
    brandSlug: "cerave",
    stock: 50,
    isFeatured: false,
    isActive: true,
    sku: "CER-FC-236",
    tags: ["Skin Care", "Cleanser"]
  },
  {
    name: "Clean & Clear Morning Energy Face Wash, 100ml",
    slug: "clean-clear-morning-energy-face-wash-100ml",
    description: "Refreshing face wash with energizing burst of citrus. Wakes up tired skin.",
    price: 650,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_19_2m3n4o5p-6q7r-8s9t-0u1v-2w3x4y5z6a7b.png"],
    categorySlug: "skin-care",
    brandSlug: "clean-clear",
    stock: 100,
    isFeatured: false,
    isActive: true,
    sku: "CLC-MEF-100",
    tags: ["Skin Care", "Face Wash"]
  },
  {
    name: "COSRX Advanced Snail 96 Mucin Power Essence, 100ml",
    slug: "cosrx-snail-96-mucin-essence-100ml",
    description: "Lightweight essence with 96% snail mucin. Repairs and hydrates damaged skin.",
    price: 3850,
    comparePrice: 4200,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_20_3n4o5p6q-7r8s-9t0u-1v2w-3x4y5z6a7b8c.png"],
    categorySlug: "skin-care",
    brandSlug: "cosrx",
    stock: 45,
    isFeatured: true,
    isActive: true,
    sku: "COS-SM-100",
    tags: ["Skin Care", "Korean Skincare", "Essence"]
  },
  {
    name: "COSRX The 6 Peptide Skin Booster Serum, 150ml",
    slug: "cosrx-6-peptide-skin-booster-serum-150ml",
    description: "Multi-tasking serum with six powerful peptides. Targets pores, fine lines, and uneven skin tone.",
    price: 7249,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_3_04030cff-8250-4ef7-a3f6-62a8bf3da6ad.png"],
    categorySlug: "skin-care",
    brandSlug: "cosrx",
    stock: 30,
    isFeatured: true,
    isActive: true,
    sku: "COS-6P-150",
    tags: ["Skin Care", "Korean Skincare", "Serum"]
  },
  {
    name: "Dove Intense Repair Shampoo, 650ml",
    slug: "dove-intense-repair-shampoo-650ml",
    description: "Nourishes hair from root to tip for beautiful, strong hair. For damaged hair.",
    price: 1250,
    comparePrice: 1400,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_21_4o5p6q7r-8s9t-0u1v-2w3x-4y5z6a7b8c9d.png"],
    categorySlug: "hair-care",
    brandSlug: "dove",
    stock: 90,
    isFeatured: false,
    isActive: true,
    sku: "DOV-IRS-650",
    tags: ["Hair Care", "Shampoo"]
  },
  {
    name: "Dove Beauty Bar, 135g",
    slug: "dove-beauty-bar-135g",
    description: "With moisturizing cream for softer, smoother skin. Gentle enough for everyday use.",
    price: 350,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_22_5p6q7r8s-9t0u-1v2w-3x4y-5z6a7b8c9d0e.png"],
    categorySlug: "skin-care",
    brandSlug: "dove",
    stock: 150,
    isFeatured: false,
    isActive: true,
    sku: "DOV-BB-135",
    tags: ["Skin Care", "Soap"]
  },
  {
    name: "Garnier Micellar Cleansing Water, 400ml",
    slug: "garnier-micellar-cleansing-water-400ml",
    description: "All-in-1 cleanser and makeup remover. Gently removes makeup and cleanses skin.",
    price: 1650,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_23_6q7r8s9t-0u1v-2w3x-4y5z-6a7b8c9d0e1f.png"],
    categorySlug: "skin-care",
    brandSlug: "garnier",
    stock: 70,
    isFeatured: true,
    isActive: true,
    sku: "GAR-MCW-400",
    tags: ["Skin Care", "Cleanser"]
  },
  {
    name: "Garnier Bright Complete Vitamin C Serum, 30ml",
    slug: "garnier-bright-complete-vitamin-c-serum-30ml",
    description: "3X faster brightening action. Reduces dark spots in just 3 days.",
    price: 1999,
    comparePrice: 2299,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_24_7r8s9t0u-1v2w-3x4y-5z6a-7b8c9d0e1f2g.png"],
    categorySlug: "skin-care",
    brandSlug: "garnier",
    stock: 65,
    isFeatured: true,
    isActive: true,
    sku: "GAR-VCS-30",
    tags: ["Skin Care", "Serum"]
  },
  {
    name: "Jenpharm Spectra Block SPF 60, 60g",
    slug: "jenpharm-spectra-block-spf60-60g",
    description: "Broad spectrum UVA/UVB protection with antioxidants. Suitable for all skin types.",
    price: 1850,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_25_8s9t0u1v-2w3x-4y5z-6a7b-8c9d0e1f2g3h.png"],
    categorySlug: "sunscreen",
    brandSlug: "jenpharm",
    stock: 45,
    isFeatured: true,
    isActive: true,
    sku: "JEN-SB-60",
    tags: ["Sunscreen", "SPF"]
  },
  {
    name: "Johnson's Baby Lotion, 500ml",
    slug: "johnsons-baby-lotion-500ml",
    description: "Clinically proven mild for newborn skin with 24hr moisture. Gentle and effective.",
    price: 950,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_26_9t0u1v2w-3x4y-5z6a-7b8c-9d0e1f2g3h4i.png"],
    categorySlug: "baby",
    brandSlug: "johnson-s",
    stock: 85,
    isFeatured: false,
    isActive: true,
    sku: "JNS-BL-500",
    tags: ["Baby", "Lotion"]
  },
  {
    name: "Johnson's Baby Shampoo, 500ml",
    slug: "johnsons-baby-shampoo-500ml",
    description: "No More Tears formula. Gentle enough for everyday use on baby's delicate hair and scalp.",
    price: 1650,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_27_0u1v2w3x-4y5z-6a7b-8c9d-0e1f2g3h4i5j.png"],
    categorySlug: "baby",
    brandSlug: "johnson-s",
    stock: 80,
    isFeatured: false,
    isActive: true,
    sku: "JNS-BS-500",
    tags: ["Baby", "Shampoo"]
  },
  {
    name: "Johnson's Baby Oil, 300ml",
    slug: "johnsons-baby-oil-300ml",
    description: "Locks in up to 10x more moisture. Leaves skin soft, smooth, and feeling healthier.",
    price: 899,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_28_1v2w3x4y-5z6a-7b8c-9d0e-1f2g3h4i5j6k.png"],
    categorySlug: "baby",
    brandSlug: "johnson-s",
    stock: 75,
    isFeatured: false,
    isActive: true,
    sku: "JNS-BO-300",
    tags: ["Baby", "Oil"]
  },
  {
    name: "Johnson's Baby Bath, 500ml",
    slug: "johnsons-baby-bath-500ml",
    description: "Gentle baby bath formula. No More Tears formula is as gentle on the eyes as pure water.",
    price: 1245,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_47.png"],
    categorySlug: "baby",
    brandSlug: "johnson-s",
    stock: 70,
    isFeatured: false,
    isActive: true,
    sku: "JNS-BB-500",
    tags: ["Baby", "Bath"]
  },
  {
    name: "Kendamil Organic Stage 1, 800g",
    slug: "kendamil-organic-stage-1-800g",
    description: "British organic infant formula. Made with whole milk and no palm oil.",
    price: 4850,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_29_2w3x4y5z-6a7b-8c9d-0e1f-2g3h4i5j6k7l.png"],
    categorySlug: "baby",
    brandSlug: "kendamil",
    stock: 35,
    isFeatured: true,
    isActive: true,
    sku: "KEN-OS1-800",
    tags: ["Baby", "Powder Milk", "Organic"]
  },
  {
    name: "Kendamil Classic Stage 2, 900g",
    slug: "kendamil-classic-stage-2-900g",
    description: "British follow-on formula for 6-12 months. Contains full cream milk for natural nutrition.",
    price: 4250,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_30_3x4y5z6a-7b8c-9d0e-1f2g-3h4i5j6k7l8m.png"],
    categorySlug: "baby",
    brandSlug: "kendamil",
    stock: 40,
    isFeatured: false,
    isActive: true,
    sku: "KEN-CS2-900",
    tags: ["Baby", "Powder Milk"]
  },
  {
    name: "Mistine Super Model Miracle Lash Mascara",
    slug: "mistine-super-model-miracle-lash-mascara",
    description: "Long-lasting mascara for dramatic lashes. Waterproof formula that doesn't smudge.",
    price: 1299,
    comparePrice: 1500,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_31_4y5z6a7b-8c9d-0e1f-2g3h-4i5j6k7l8m9n.png"],
    categorySlug: "makeup",
    brandSlug: "mistine",
    stock: 55,
    isFeatured: false,
    isActive: true,
    sku: "MIS-MAS-01",
    tags: ["Makeup", "Mascara"]
  },
  {
    name: "Neutrogena Hydro Boost Water Gel, 50g",
    slug: "neutrogena-hydro-boost-water-gel-50g",
    description: "Lightweight gel cream that quenches skin for supple, smooth skin. With hyaluronic acid.",
    price: 3250,
    comparePrice: 3600,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_32_5z6a7b8c-9d0e-1f2g-3h4i-5j6k7l8m9n0o.png"],
    categorySlug: "skin-care",
    brandSlug: "neutrogena",
    stock: 50,
    isFeatured: true,
    isActive: true,
    sku: "NEU-HBW-50",
    tags: ["Skin Care", "Moisturizer"]
  },
  {
    name: "Neutrogena Deep Clean Facial Cleanser, 200ml",
    slug: "neutrogena-deep-clean-facial-cleanser-200ml",
    description: "Removes impurities and oil without over-drying. Dermatologist recommended.",
    price: 1850,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_33_6a7b8c9d-0e1f-2g3h-4i5j-6k7l8m9n0o1p.png"],
    categorySlug: "skin-care",
    brandSlug: "neutrogena",
    stock: 65,
    isFeatured: false,
    isActive: true,
    sku: "NEU-DCF-200",
    tags: ["Skin Care", "Cleanser"]
  },
  {
    name: "Nike Up or Down Men EDT, 75ml",
    slug: "nike-up-or-down-men-edt-75ml",
    description: "Fresh and energetic fragrance for men. Perfect for everyday wear.",
    price: 2850,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_34_7b8c9d0e-1f2g-3h4i-5j6k-7l8m9n0o1p2q.png"],
    categorySlug: "fragrance",
    brandSlug: "nike",
    stock: 40,
    isFeatured: false,
    isActive: true,
    sku: "NIK-UOD-75",
    tags: ["Fragrance", "Perfume", "Men"]
  },
  {
    name: "Nivea Soft Moisturizing Cream, 200ml",
    slug: "nivea-soft-moisturizing-cream-200ml",
    description: "Refreshingly soft moisturizing cream for face, body, and hands. Light and non-greasy.",
    price: 899,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_35_8c9d0e1f-2g3h-4i5j-6k7l-8m9n0o1p2q3r.png"],
    categorySlug: "skin-care",
    brandSlug: "nivea",
    stock: 100,
    isFeatured: false,
    isActive: true,
    sku: "NIV-SMC-200",
    tags: ["Skin Care", "Moisturizer"]
  },
  {
    name: "Nivea Men Deep Impact Face Wash, 100ml",
    slug: "nivea-men-deep-impact-face-wash-100ml",
    description: "Deep cleansing face wash for men. Removes dirt, oil, and impurities.",
    price: 650,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_36_9d0e1f2g-3h4i-5j6k-7l8m-9n0o1p2q3r4s.png"],
    categorySlug: "skin-care",
    brandSlug: "nivea",
    stock: 90,
    isFeatured: false,
    isActive: true,
    sku: "NIV-MDF-100",
    tags: ["Skin Care", "Face Wash", "Men"]
  },
  {
    name: "Pond's White Beauty Cream, 50g",
    slug: "ponds-white-beauty-cream-50g",
    description: "Brightening cream with vitamin B3. For visibly lighter and brighter skin.",
    price: 750,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_37_0e1f2g3h-4i5j-6k7l-8m9n-0o1p2q3r4s5t.png"],
    categorySlug: "skin-care",
    brandSlug: "pond-s",
    stock: 85,
    isFeatured: false,
    isActive: true,
    sku: "PON-WBC-50",
    tags: ["Skin Care", "Cream"]
  },
  {
    name: "Sudocrem Antiseptic Healing Cream, 125g",
    slug: "sudocrem-antiseptic-healing-cream-125g",
    description: "Clinically proven to soothe and heal. For nappy rash, minor burns, and skin irritations.",
    price: 1650,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_38_1f2g3h4i-5j6k-7l8m-9n0o-1p2q3r4s5t6u.png"],
    categorySlug: "baby",
    brandSlug: "sudocrem",
    stock: 70,
    isFeatured: true,
    isActive: true,
    sku: "SUD-AHC-125",
    tags: ["Baby", "Healing Cream"]
  },
  {
    name: "Sudocrem Antiseptic Healing Cream, 250g",
    slug: "sudocrem-antiseptic-healing-cream-250g",
    description: "Clinically proven to soothe and heal. Larger size for families.",
    price: 2850,
    comparePrice: 3100,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/Untitleddesign_39_2g3h4i5j-6k7l-8m9n-0o1p-2q3r4s5t6u7v.png"],
    categorySlug: "baby",
    brandSlug: "sudocrem",
    stock: 55,
    isFeatured: false,
    isActive: true,
    sku: "SUD-AHC-250",
    tags: ["Baby", "Healing Cream"]
  },
  {
    name: "Centella Toning Toner, 400ml",
    slug: "centella-toning-toner-400ml",
    description: "Soothing and hydrating toner enriched with Centella Asiatica. For sensitive, acne-prone skin.",
    price: 6695,
    comparePrice: null,
    images: ["https://cdn.shopify.com/s/files/1/0614/4301/4703/files/aca.png"],
    categorySlug: "skin-care",
    brandSlug: "centella",
    stock: 40,
    isFeatured: true,
    isActive: true,
    sku: "CEN-TT-400",
    tags: ["Skin Care", "Toner"]
  },
  ...extendedProducts
];

// Combine base brands with extended brands
export const allBrands = [...seedBrands, ...extendedBrands.filter(eb => 
  !seedBrands.some(sb => sb.slug === eb.slug)
)];
